Data:
  dataset_dir: datasets/
  train_split_ratio: 0.8
Test:
  confidence: auto
  face_model_dir: face_detector
  mask_model: model\mask_detector_best.h5
Train:
  cv:
    k-fold: 5
    seed: 7
  hyperparameter:
    BS: 32
    INIT_LR: 1e-4
    epoch: 50
  model: ResNet50V2
  model_dir: model/
  plot: fig/train_metrics.png
  val_split: 0.2
